FROM node:20-alpine AS build

# Créer le répertoire de travail
WORKDIR /app

# Copier uniquement les fichiers nécessaires pour installer les dépendances
COPY package*.json ./

# Installer les dépendances de production uniquement
RUN npm install

# Copier le reste des fichiers (à l'exception de ceux ignorés par .dockerignore)
COPY . .

RUN npm run build

# On monte l'image de prod
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]