services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=lafibredudev@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`dashboard.lafibredudev.com`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      # identifiants : admin monMotDePasse (> htpasswd -nbB admin monMotDePasse)
      #- "traefik.http.middlewares.auth.basicauth.users=admin:$2y$05$hW65dSyRnY4sccQVWtMhU.Y0aBfJBUdaeEcawhoJ1M5qNPRjUVC26"
      #- "traefik.http.routers.traefik-dashboard.middlewares=auth"
    restart: unless-stopped

  # "traefik.http.services.<ton-nom-de-service>.loadbalancer.server.port: 8888"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_BACKEND_BASE_URL: https://backend2.lafibredudev.com
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend2.lafibredudev.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    container_name: backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend2.lafibredudev.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    environment:
      - NODE_ENV=production
      - DATABASE_DBNAME=devdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devdb